---
- name: In-Memory Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    guid: "{{ lookup('env','GUID') }}"
    home: "{{ lookup('env','HOME') }}"
    internal_domain: "{{ lookup('env','INTERNAL_DOMAIN') }}"
  tasks:
    - meta: refresh_inventory

    - name: Collection instance info
      openstack.cloud.server_info:
        cloud: "{{ guid }}-project"
      register: instances

    - name: Build In-Memory inventory
      ansible.builtin.add_host:
        host: "{{ item.name }}"
        group: 
          - "{{ item.metadata.AnsibleGroup }}"
          - osp_instances
        ansible_host: "{{ item.private_v4 }}"
        ansible_user: cloud-user
        ansible_ssh_private_key_file: "/home/runner/.ssh/{{ guid }}key.pem"
      when: item.metadata.type | default('') == "osp_instances"
      loop: "{{ instances.openstack_servers }}"

